# Generated by Django 5.0.4 on 2024-04-24 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_category_gender_alter_customuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='brands'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 17, 51, 7, 520148, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 24, 17, 51, 7, 525142, tzinfo=datetime.timezone.utc)),
        ),
    ]
